version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fcnodedb
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: ./app
    restart: always
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 
      DB_NAME: fcnodedb
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db-data:
